server:
  port: 8191
spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      username: root
      password: rootpassword
      database: admin
      repositories:
        enabled: true
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG