spring:
  application:
    name: Spring Boot Kafka MongoDB consumer
  data:
    mongodb:
      host: localhost
      port: 27017
      database: admin
      repositories:
        enabled: true
  kafka:
    consumer:
      enable-auto-commit: false
    listener:
      ack-mode: MANUAL_IMMEDIATE

server:
  port: 8192
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG